version: "3.9"

services:
  frontend:
    image: kodelio/kodelio-frontend:prod
    hostname: "{{.Task.Name}}"
    read_only: true
    ports:
      - "3001:3001"
    cap_drop:
      - ALL
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "700m"
        reservations:
          memory: "450m"
      restart_policy:
        max_attempts: 5
        window: 30s
      update_config:
        parallelism: 1
        order: start-first

    networks:
      - frontend
      
    volumes:
      - tmpfs_tmp:/tmp

    env_file:
      - .env

networks:
  frontend:
    driver: overlay
    attachable: true
    name: frontend
    
volumes:
  tmpfs_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
