name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:            
      - name: Deploy to Docker
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          copy_stack_file: true
          deploy_path: /home/ubuntu/github
          keep_files: 5
          args: kodelio_prod
