name: dev - Build, Publish & Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  task:
    name: Build, Publish & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build the image
        run: docker build -t kodelio/kodelio-frontend:dev --build-arg PORT=3000 -f ./docker/Dockerfile .

      - name: Tag the image with the latest commit sha
        run: docker tag kodelio/kodelio-frontend:dev kodelio/kodelio-frontend:${{ github.sha }}

      - name: Push image to DockerHub
        run: docker push --all-tags kodelio/kodelio-frontend

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          docker -H "ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Deploy stack
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: docker -H "ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" stack deploy --with-registry-auth --compose-file docker/docker-compose-dev.yaml kodelio_dev
