name: Publish Docker Images
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
    # branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build the image
        run: docker build -t kodelio/kodelio-frontend:latest -f ./docker/Dockerfile .

      - name: Tag the image with the latest commit sha
        run: docker tag kodelio/kodelio-frontend kodelio/kodelio-frontend:${{ github.sha }}

      - name: Push image to DockerHub
        run: docker push --all-tags kodelio/kodelio-frontend
